CREATE TABLE IF NOT EXISTS champion (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    "key" INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    patch_version VARCHAR(20) NOT NULL,
    champion_history TEXT NOT NULL DEFAULT '[]',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS jungle_match_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id VARCHAR(30) NOT NULL,
    champion_id VARCHAR(50) NOT NULL,
    team VARCHAR(4) NOT NULL,
    win BOOLEAN NOT NULL,
    opponent_champion_id VARCHAR(50) NOT NULL,
    runes TEXT NOT NULL,
    summoner_spells VARCHAR(10) NOT NULL,
    start_position VARCHAR(20),
    banned_champions TEXT NOT NULL DEFAULT '[]',
    patch_version VARCHAR(20) NOT NULL,
    summoner_name VARCHAR(50) NOT NULL,
    summoner_tag VARCHAR(10) NOT NULL,
    summoner_tier VARCHAR(20),
    game_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pure_fullcamp_clear_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jungle_match_record_id BIGINT NOT NULL UNIQUE,
    clear_time_ms INT NOT NULL,
    youtube_video_id VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS champion_stats (
    champion_id VARCHAR(50) NOT NULL,
    patch_version VARCHAR(20) NOT NULL,
    pick_count INT NOT NULL DEFAULT 0,
    win_count INT NOT NULL DEFAULT 0,
    ban_count INT NOT NULL DEFAULT 0,
    total_matches INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (champion_id, patch_version)
);

CREATE TABLE IF NOT EXISTS champion_matchup (
    champion_id VARCHAR(50) NOT NULL,
    opponent_champion_id VARCHAR(50) NOT NULL,
    patch_version VARCHAR(20) NOT NULL,
    wins INT NOT NULL DEFAULT 0,
    losses INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (champion_id, opponent_champion_id, patch_version)
);

CREATE TABLE IF NOT EXISTS champion_clear_stats (
    champion_id VARCHAR(50) NOT NULL,
    patch_version VARCHAR(20) NOT NULL,
    team VARCHAR(4) NOT NULL,
    start_position VARCHAR(20) NOT NULL,
    avg_clear_time_ms INT NOT NULL DEFAULT 0,
    best_clear_time_ms INT NOT NULL DEFAULT 0,
    sample_count INT NOT NULL DEFAULT 0,
    start_count INT NOT NULL DEFAULT 0,
    total_games INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (champion_id, patch_version, team, start_position)
);
