spring:
  application:
    name: jungleclear-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_schema: public

riot:
  api-key: ${RIOT_API_KEY}
  kr-base-url: https://kr.api.riotgames.com
  asia-base-url: https://asia.api.riotgames.com
  ddragon-base-url: https://ddragon.leagueoflegends.com

server:
  port: 8080
